### ISSUE TITLE
Passing EntityContext to EvalContext

### ISSUE THREAD

**Issue by DoHe** [checkr/goflagr#6]
I'm trying to use the `PostEvaluation` function of the `EvaluationApi`. This expects a `EvalContext` which has a `EntityContext` field of type `*interface{}`: https://github.com/checkr/goflagr/blob/master/model_eval_context.go#L16
I'm kind of at a loss what I should be passing here. From what I've seen in other packages, even if you expect a pointer you just define `interface{}` as that accepts pointers as well. I've tried everything I could imagine (`map[string]string`, `*map[string]string`, `**map[string]string`), but nothing compiles.
I have the feeling that this is just a bug and should really be just `interface{}` but either way it would be great to have an example for what is expected.

**Comment by zhouzhuojie** [comment]
Thanks for reporting, this is auto-generated from openapi/swagger, I will see what I can do to fix this.

**Comment by zhouzhuojie** [comment]
How about this

```
package goflagr                                     
                                                    
import "testing"                                    
                                                    
func TestEvalContext(t *testing.T) {                
    entityContext := interface{}(map[string]string{ 
        "foo": "bar",                               
    })                                              
    ctx := EvalContext{                             
        EntityID:      "123",                       
        EntityType:    "type1",                     
        EntityContext: &entityContext,              
        FlagID:        1,                           
    }                                               
    if ctx.EntityContext == nil {                   
        t.Error("empty EvalContext")                
    }                                               
}                                                   
```

I've also added a test file https://github.com/checkr/goflagr/blob/0987e665a489211bccbbbaceef4c5a9522556aab/tests/model_eval_context_test.go

PR: https://github.com/checkr/goflagr/pull/7

**Comment by DoHe** [comment]
@zhouzhuojie thanks a lot, this works!
